name: Deploy

on:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    permissions:
      id-token: write # This is required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'beta'
          architecture: x64

      - run: flutter --version

      - name: Install dependencies
        run: flutter pub get
        working-directory: ${{ inputs.working-directory }}
      - name: Publish - dry run
        run: flutter pub publish --dry-run
        working-directory: ${{ inputs.working-directory }}
      - name: Publish to pub.dev
        run: flutter pub publish -f
        working-directory: ${{ inputs.working-directory }}
